version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONBREAKPOINT=0
    volumes:
      - .:/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge 